# Generated by Django 4.1.7 on 2023-03-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
